# Generated by Django 3.0.3 on 2023-12-17 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40, verbose_name='学籍番号')),
                ('nationality', models.CharField(max_length=40, verbose_name='国籍')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('kana', models.CharField(max_length=40, verbose_name='フリガナ')),
                ('gender', models.CharField(max_length=40, verbose_name='男女')),
                ('email', models.CharField(max_length=40, verbose_name='メールアドレス')),
                ('abbre', models.CharField(max_length=40, verbose_name='ユーザーネーム')),
            ],
        ),
    ]
